### ISSUE TITLE
Can this project support IOS screen mirroring function?

### ISSUE THREAD

**Issue by ootorichan** [openairplay/airplay2-receiver#58]
Ft07ScreenMirroring in FEATURES works successfully, but the bplist returned by the TEARDOWN stage after the iphone is enabled is null.

**Comment by ootorichan** [comment]
Is an AirTunes service missing?

**Comment by systemcrash** [comment]
"Airtunes", in the sense of audio, works. There is next to no code implemented to support screen mirroring. The flags are documented, but they won't magically get video working. Video requires AES and SHA512 to work properly, and it's not there yet. 

I've been working on OMGHAX in python, so that at least AES would be implemented and that needs lots of testing/verification. But I will likely not implement video support. 

PRs are welcome.
